server:
  port: ${SERVER_PORT:8081}
  servlet:
    contextPath: ${CONTEXT_PATH:/api}
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        proc:
          param_null_passing: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
  datasource:
    username: ${DS_USER:sa}
    password: ${DS_PASSWORD:password}
    url: jdbc:h2:mem:assesmentdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false

